CREATE TABLE [dbo].[TLRM_USG_MCCMNCNoVPLMN]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[MCCMNC] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreateDate] [datetime] NULL CONSTRAINT [DF_TLRM_USG_MCCMNCNoVPLMN_CreateDate] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TLRM_USG_MCCMNCNoVPLMN] ADD CONSTRAINT [PK_TLRM_USG_MCCMNCNoVPLMN] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
