CREATE TABLE [dbo].[TLRM_USG_CDRs]
(
[cdrID] [bigint] NOT NULL IDENTITY(1, 1),
[cdrVersion] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrUsageKey] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrAccountingRecordTypeID] [int] NULL,
[cdrStatusID] [int] NULL,
[cdrStatusDate] [datetime] NULL,
[cdrFileID] [int] NULL,
[cdrNetworkElement] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrStartTime] [datetime] NULL,
[cdrEndTime] [datetime] NULL,
[cdrUsageUplink] [bigint] NULL,
[cdrUsageDownlink] [bigint] NULL,
[cdrUsageDate] [datetime] NULL,
[cdrIMSI] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrIMEI] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrIP] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrMCCMNC] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrSGSNIP] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrData] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sdID] [int] NULL,
[subscriberID] [int] NULL,
[affiliateID] [int] NULL,
[customerID] [int] NULL,
[orderID] [int] NULL,
[orderNumber] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productID] [int] NULL,
[internalOrderID] [int] NULL,
[accountID] [int] NULL,
[branchID] [int] NULL,
[cdrIMSIServiceProviderID] [int] NULL,
[cdrSIMID] [int] NULL,
[cdrSIMSerial] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrICCID] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdrSIMServiceProfileID] [int] NULL,
[cdrSIMServiceProviderID] [int] NULL,
[cdrUsageDeviceID] [int] NULL,
[cdrUsageDeviceSerial] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carrierID] [int] NULL,
[vplmnID] [int] NULL,
[vplmnName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vplmnTADIGCode] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[countryID] [int] NULL,
[countryName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[countryCode] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[threadID] [int] NULL,
[cdrCreatedate] [datetime] NULL,
[cdrRecordOpeningTime] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TLRM_USG_CDRs] ADD CONSTRAINT [PK_TLRM_USG_CDRs] PRIMARY KEY CLUSTERED  ([cdrID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20201214-120439] ON [dbo].[TLRM_USG_CDRs] ([cdrStatusID], [cdrID]) WITH (FILLFACTOR=50, PAD_INDEX=ON) ON [PRIMARY]
GO
