CREATE TABLE [dbo].[TLRM_USG_UsageLog_TMP]
(
[ulogID] [bigint] NOT NULL IDENTITY(1, 1),
[ulogStatusID] [int] NULL,
[ulogStatusDate] [datetime] NULL,
[ulogIP] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogIMEI] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogMACAddress] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogICCID] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogMSISDN] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogIMSI] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reportEventID] [int] NULL,
[ulogFirmwareVersion] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogMCC] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogMNC] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogApplianceID] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogNetwork] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nsmID] [int] NULL,
[ctypeID] [int] NULL,
[ulogSS] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogBatLevel] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_ulogBatLevel] DEFAULT ((0)),
[ulogTotalDevices] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_ulogTotalDevices] DEFAULT ((-1)),
[batteryChrgID] [int] NULL,
[ulogSSID] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogMF30Ver] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogMF60Ver] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogCellid] [int] NULL,
[quotaTypeID] [int] NULL,
[ulogQuota] [float] NULL,
[ulogTimeZone] [int] NULL,
[ulogUsageDateTime] [datetime] NULL,
[customerID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_customerID] DEFAULT ((0)),
[orderID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_orderID] DEFAULT ((0)),
[orderNumber] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderProductID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_orderProductID] DEFAULT ((0)),
[productID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_productID] DEFAULT ((0)),
[orderUsageTypeID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_orderUsageTypeID] DEFAULT ((0)),
[ulogIsRoaming] [bit] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_ulogIsRoaming] DEFAULT ((0)),
[countryID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_countryID] DEFAULT ((0)),
[carrierID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_carrierID] DEFAULT ((0)),
[ulogDeviceID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_ulogDeviceID] DEFAULT ((0)),
[ulogDeviceNumber] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ulogSIMDeviceID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_ulogSIMDeviceID] DEFAULT ((0)),
[ulogSIMDeviceNumber] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usageWebbingSIM] [bit] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_usageWebbingSIM] DEFAULT ((0)),
[usageKey] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[uLogCreateDate] [datetime] NULL,
[ulogQID] [bigint] NULL,
[InternalOrderID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_InternalOrderID] DEFAULT ((0)),
[accountID] [int] NULL,
[branchID] [int] NULL,
[serviceProviderID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_serviceProviderID] DEFAULT ((0)),
[threadID] [int] NULL CONSTRAINT [DF_TLRM_USG_UsageLog_TMP_threadID_1] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TLRM_USG_UsageLog_TMP] ADD CONSTRAINT [PK_TLRM_USG_UsageLog_TMP] PRIMARY KEY CLUSTERED  ([ulogID]) WITH (FILLFACTOR=50, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20150512-204334] ON [dbo].[TLRM_USG_UsageLog_TMP] ([threadID], [ulogStatusID], [ulogID]) WITH (FILLFACTOR=50, PAD_INDEX=ON) ON [PRIMARY]
GO
